/**
 * Load the compiled TicTacToe artifact.
 *
 * The artifact is the single source of truth for state field definitions,
 * constructor slot offsets, and script templates. It is generated by
 * `runar compile` and lives in the frontend's generated directory.
 */
import { readFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import type { RunarArtifact } from 'runar-sdk'

const __dirname = dirname(fileURLToPath(import.meta.url))
const artifactPath = resolve(__dirname, '..', '..', 'frontend', 'src', 'generated', 'TicTacToe.runar.json')
export const artifact = JSON.parse(readFileSync(artifactPath, 'utf-8')) as RunarArtifact
